name: Update Napoli Serie A Fixtures

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 UTC
  workflow_dispatch:

jobs:
  fetch_napoli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch fixtures via action
        id: fixtures
        uses: fjogeleit/http-request-action@v1
        with:
            url: "https://v3.football.api-sports.io/fixtures?team=167&league=135&season=2025&status=all"
            method: GET
            customHeaders: |
                x-apisports-key: ${{ secrets.API_FOOTBALL_KEY }}

      - name: Save raw response
        run: echo "${{ steps.fixtures.responseBody }}" > napoli-fixtures.json

      - name: Parse upcoming/finished matches
        run: |
          jq -r '.response[] |
            select(.league.id==135) |
            "\\(.fixture.date) — \(.teams.home.name) vs \(.teams.away.name) — status: \(.fixture.status.short)"' \
            napoli-fixtures.json > napoli-fixtures.md

      - name: Commit report
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions'
          author_email: 'actions@github.com'
          message: 'Update Napoli fixtures'
          push: true
